import json
import os
from abc import ABC, abstractmethod


class LLMClientError(Exception):
    pass


class BaseLLMClient(ABC):
    provider_name = "base"

    @abstractmethod
    def generate(self, payload: dict) -> str:
        raise NotImplementedError


class FakeLLMClient(BaseLLMClient):
    provider_name = "fake"

    def generate(self, payload: dict) -> str:
        agent = payload.get("agent_name")
        task = payload.get("task") or {}
        title = task.get("title", "Untitled task")
        description = task.get("description", "")
        repo_ctx = task.get("artifacts", {}).get("repository_context", {})
        relevant_files = repo_ctx.get("relevant_files", []) if isinstance(repo_ctx, dict) else []
        first_relevant_path = None
        if relevant_files and isinstance(relevant_files[0], dict):
            first_relevant_path = relevant_files[0].get("path")

        if agent == "analyst":
            data = {
                "artifacts": {
                    "analysis": f"Structured analysis for '{title}': {description}",
                    "acceptance_criteria": [
                        "Core flow is clearly defined and testable.",
                        "Outcome is observable and verifiable.",
                    ],
                },
                "message": "Analyst refined the raw idea into structured requirements.",
                "status": "done",
            }
        elif agent == "architect":
            architecture_note = "Use a simple modular structure with explicit workflow boundaries."
            if repo_ctx.get("attached") and first_relevant_path:
                architecture_note = (
                    "Use current repository structure and start from existing files such as "
                    f"'{first_relevant_path}'."
                )
            data = {
                "artifacts": {
                    "architecture": architecture_note,
                    "technical_risks": [
                        "Task fields may drift without schema checks.",
                        "Workflow integrity can break if transitions are bypassed.",
                    ],
                    "implementation_guidance": "Implement in small deterministic steps with validation-first checks.",
                },
                "message": "Architect prepared implementation guidance.",
                "status": "in_progress",
            }
        elif agent == "developer":
            files_to_modify = [first_relevant_path] if first_relevant_path else ["unknown"]
            data = {
                "artifacts": {
                    "implementation": "Developer prepared deterministic implementation notes.",
                    "implementation_plan": {
                        "summary": "Implementation plan generated by fake provider.",
                        "files_to_create": [],
                        "files_to_modify": files_to_modify,
                        "proposed_changes": [
                            {
                                "file_path": first_relevant_path or "unknown",
                                "change_type": "modify",
                                "reason": "Task requires implementation changes.",
                                "description": "Review project structure and apply the required behavior.",
                                "safe_to_apply": False,
                            }
                        ],
                        "commands_to_run": ["python -m unittest discover -s tests"],
                        "tests_to_add": ["Add or update unit tests for the changed behavior."],
                        "risks": ["Exact files are unknown without deeper repository inspection."],
                        "rollback_notes": "Revert modified files if validation fails.",
                    },
                    "patch_proposal": {
                        "summary": "Fake provider does not generate real file changes.",
                        "files": [],
                        "unified_diff": "",
                        "requires_approval": True,
                        "approved": False,
                        "applied": False,
                        "applied_at": None,
                    },
                },
                "message": "Developer prepared implementation plan and patch proposal.",
                "status": "review",
            }
        elif agent == "qa":
            command_results = task.get("artifacts", {}).get("command_results", [])
            has_failed = any(isinstance(item, dict) and item.get("success") is False for item in command_results)
            has_passed_test = any(
                isinstance(item, dict)
                and item.get("success") is True
                and "python -m unittest discover -s tests" in str(item.get("command", ""))
                for item in command_results
            )

            if has_failed:
                verdict = "failed"
                summary = "QA observed failed command results."
                checked_items = ["Command results were reviewed."]
                failed_checks = ["At least one validation command failed."]
            elif has_passed_test:
                verdict = "passed"
                summary = "QA observed successful validation command results."
                checked_items = ["Unit test command succeeded.", "Basic QA scenarios were covered."]
                failed_checks = []
            else:
                verdict = "needs_rework"
                summary = "Fake QA generated checks but did not execute real tests."
                checked_items = ["Implementation plan exists.", "Basic test scenarios were proposed."]
                failed_checks = ["No real test command output was provided."]

            data = {
                "artifacts": {
                    "test_cases": [
                        "Validate happy path behavior.",
                        "Validate invalid input handling.",
                    ],
                    "edge_cases": [
                        "Empty required fields.",
                        "Repeated execution on same task.",
                    ],
                    "bugs": [],
                    "qa_verification": {
                        "verdict": verdict,
                        "summary": summary,
                        "checked_items": checked_items,
                        "failed_checks": failed_checks,
                        "bugs_found": [],
                        "recommended_next_status": "review",
                    },
                },
                "message": "QA prepared verification report.",
                "status": "done",
            }
        elif agent == "bug_intake":
            data = {
                "artifacts": {
                    "bug_report": {
                        "summary": "Structured bug summary from raw input.",
                        "environment": "unknown",
                        "steps_to_reproduce": [
                            "Open affected functionality",
                            "Perform the reported action",
                            "Observe the actual result",
                        ],
                        "actual_result": "Reported behavior occurs.",
                        "expected_result": "System should behave according to requirements.",
                        "logs": [],
                        "attachments": [],
                        "suspected_area": "unknown",
                        "impact": "Needs investigation.",
                    }
                },
                "severity": "unknown",
                "priority": "medium",
                "message": "Bug Intake created a structured bug report.",
            }
        elif agent == "supervisor":
            user_text = str(payload.get("user_text", "")).lower()
            if "run all" in user_text or "run_all" in user_text:
                data = {
                    "intent": "run_all",
                    "confidence": 0.8,
                    "requires_confirmation": True,
                    "action": {"name": "run_all", "args": {}},
                    "explanation": "Running all tasks is a risky bulk action.",
                    "warnings": ["Requires explicit confirmation."],
                }
            elif any(token in user_text for token in ("bug", "баг", "error", "500")):
                data = {
                    "intent": "create_bug",
                    "confidence": 0.9,
                    "requires_confirmation": False,
                    "action": {
                        "name": "create_bug",
                        "args": {
                            "title": "Login returns 500",
                            "description": "Login fails with HTTP 500.",
                            "raw": "NullPointerException",
                        },
                    },
                    "explanation": "The request describes a bug report.",
                    "warnings": [],
                }
            elif any(token in user_text for token in ("task", "задач")):
                data = {
                    "intent": "create_task",
                    "confidence": 0.9,
                    "requires_confirmation": False,
                    "action": {
                        "name": "create_task",
                        "args": {
                            "title": "Add healthcheck command",
                            "description": "Create a CLI command that prints system health status.",
                        },
                    },
                    "explanation": "The request describes a new feature task.",
                    "warnings": [],
                }
            elif any(token in user_text for token in ("next", "дальше", "что делать")):
                data = {
                    "intent": "next_task",
                    "confidence": 0.95,
                    "requires_confirmation": False,
                    "action": {"name": "next_task", "args": {}},
                    "explanation": "The user asks for the next recommended task.",
                    "warnings": [],
                }
            elif any(token in user_text for token in ("backlog", "беклог")):
                data = {
                    "intent": "backlog",
                    "confidence": 0.9,
                    "requires_confirmation": False,
                    "action": {"name": "backlog", "args": {}},
                    "explanation": "The user requests backlog view.",
                    "warnings": [],
                }
            elif any(token in user_text for token in ("release", "релиз")):
                data = {
                    "intent": "list_releases",
                    "confidence": 0.9,
                    "requires_confirmation": False,
                    "action": {"name": "list_releases", "args": {}},
                    "explanation": "The user asks about releases.",
                    "warnings": [],
                }
            else:
                data = {
                    "intent": "clarify",
                    "confidence": 0.4,
                    "requires_confirmation": False,
                    "action": {"name": "clarify", "args": {}},
                    "explanation": "The request is ambiguous. Please clarify the desired action.",
                    "warnings": [],
                }
        else:
            raise LLMClientError(f"Unsupported agent for fake provider: {agent}")

        return json.dumps(data, ensure_ascii=False)


class OpenAILLMClient(BaseLLMClient):
    provider_name = "openai"

    def __init__(self, api_key: str, model: str):
        self.api_key = api_key
        self.model = model

    def generate(self, payload: dict) -> str:
        try:
            from openai import OpenAI
        except ImportError as exc:
            raise LLMClientError(
                "OpenAI provider requires the 'openai' package. Install dependencies from requirements.txt."
            ) from exc

        client = OpenAI(api_key=self.api_key)
        instruction = (
            "Return JSON only. Output must be an object with keys: artifacts (object), message (string)."
        )
        prompt = json.dumps(payload, ensure_ascii=False)

        try:
            response = client.responses.create(
                model=self.model,
                input=[
                    {"role": "system", "content": instruction},
                    {"role": "user", "content": prompt},
                ],
            )
        except Exception as exc:
            raise LLMClientError(f"OpenAI request failed: {exc}") from exc

        text = getattr(response, "output_text", None)
        if text:
            return text

        raise LLMClientError("OpenAI response did not contain output_text.")


def get_llm_client(provider: str | None = None) -> BaseLLMClient:
    selected = (provider or os.getenv("LLM_PROVIDER") or "fake").strip().lower()

    if selected == "fake":
        return FakeLLMClient()

    if selected == "openai":
        api_key = (os.getenv("OPENAI_API_KEY") or "").strip()
        if not api_key:
            raise LLMClientError("OPENAI_API_KEY is required when LLM_PROVIDER=openai.")
        model = (os.getenv("OPENAI_MODEL") or "gpt-5.1-mini").strip() or "gpt-5.1-mini"
        return OpenAILLMClient(api_key=api_key, model=model)

    raise LLMClientError(f"Unsupported LLM provider: {selected}")
