import json
import os
from abc import ABC, abstractmethod


class LLMClientError(Exception):
    pass


class BaseLLMClient(ABC):
    provider_name = "base"

    @abstractmethod
    def generate(self, payload: dict) -> str:
        raise NotImplementedError


class FakeLLMClient(BaseLLMClient):
    provider_name = "fake"

    def generate(self, payload: dict) -> str:
        agent = payload.get("agent_name")
        task = payload.get("task") or {}
        title = task.get("title", "Untitled task")
        description = task.get("description", "")

        if agent == "analyst":
            data = {
                "artifacts": {
                    "analysis": f"Structured analysis for '{title}': {description}",
                    "acceptance_criteria": [
                        "Core flow is clearly defined and testable.",
                        "Outcome is observable and verifiable.",
                    ],
                },
                "message": "Analyst refined the raw idea into structured requirements.",
                "status": "done",
            }
        elif agent == "architect":
            data = {
                "artifacts": {
                    "architecture": "Use a simple modular structure with explicit workflow boundaries.",
                    "technical_risks": [
                        "Task fields may drift without schema checks.",
                        "Workflow integrity can break if transitions are bypassed.",
                    ],
                    "implementation_guidance": "Implement in small deterministic steps with validation-first checks.",
                },
                "message": "Architect prepared implementation guidance.",
                "status": "in_progress",
            }
        elif agent == "developer":
            data = {
                "artifacts": {
                    "implementation": "Developer prepared deterministic implementation notes.",
                    "implementation_plan": {
                        "summary": "Implementation plan generated by fake provider.",
                        "files_to_create": [],
                        "files_to_modify": ["unknown"],
                        "proposed_changes": [
                            {
                                "file_path": "unknown",
                                "change_type": "modify",
                                "reason": "Task requires implementation changes.",
                                "description": "Review project structure and apply the required behavior.",
                                "safe_to_apply": False,
                            }
                        ],
                        "commands_to_run": ["python -m unittest discover -s tests"],
                        "tests_to_add": ["Add or update unit tests for the changed behavior."],
                        "risks": ["Exact files are unknown without deeper repository inspection."],
                        "rollback_notes": "Revert modified files if validation fails.",
                    },
                },
                "message": "Developer prepared a structured implementation plan.",
                "status": "review",
            }
        elif agent == "qa":
            data = {
                "artifacts": {
                    "test_cases": [
                        "Validate happy path behavior.",
                        "Validate invalid input handling.",
                    ],
                    "edge_cases": [
                        "Empty required fields.",
                        "Repeated execution on same task.",
                    ],
                    "bugs": [],
                },
                "message": "QA prepared validation scenarios.",
                "status": "done",
            }
        elif agent == "bug_intake":
            data = {
                "artifacts": {
                    "bug_report": {
                        "summary": "Structured bug summary from raw input.",
                        "environment": "unknown",
                        "steps_to_reproduce": [
                            "Open affected functionality",
                            "Perform the reported action",
                            "Observe the actual result",
                        ],
                        "actual_result": "Reported behavior occurs.",
                        "expected_result": "System should behave according to requirements.",
                        "logs": [],
                        "attachments": [],
                        "suspected_area": "unknown",
                        "impact": "Needs investigation.",
                    }
                },
                "severity": "unknown",
                "priority": "medium",
                "message": "Bug Intake created a structured bug report.",
            }
        else:
            raise LLMClientError(f"Unsupported agent for fake provider: {agent}")

        return json.dumps(data, ensure_ascii=False)


class OpenAILLMClient(BaseLLMClient):
    provider_name = "openai"

    def __init__(self, api_key: str, model: str):
        self.api_key = api_key
        self.model = model

    def generate(self, payload: dict) -> str:
        try:
            from openai import OpenAI
        except ImportError as exc:
            raise LLMClientError(
                "OpenAI provider requires the 'openai' package. Install dependencies from requirements.txt."
            ) from exc

        client = OpenAI(api_key=self.api_key)
        instruction = (
            "Return JSON only. Output must be an object with keys: artifacts (object), message (string)."
        )
        prompt = json.dumps(payload, ensure_ascii=False)

        try:
            response = client.responses.create(
                model=self.model,
                input=[
                    {"role": "system", "content": instruction},
                    {"role": "user", "content": prompt},
                ],
            )
        except Exception as exc:
            raise LLMClientError(f"OpenAI request failed: {exc}") from exc

        text = getattr(response, "output_text", None)
        if text:
            return text

        raise LLMClientError("OpenAI response did not contain output_text.")


def get_llm_client(provider: str | None = None) -> BaseLLMClient:
    selected = (provider or os.getenv("LLM_PROVIDER") or "fake").strip().lower()

    if selected == "fake":
        return FakeLLMClient()

    if selected == "openai":
        api_key = (os.getenv("OPENAI_API_KEY") or "").strip()
        if not api_key:
            raise LLMClientError("OPENAI_API_KEY is required when LLM_PROVIDER=openai.")
        model = (os.getenv("OPENAI_MODEL") or "gpt-5.1-mini").strip() or "gpt-5.1-mini"
        return OpenAILLMClient(api_key=api_key, model=model)

    raise LLMClientError(f"Unsupported LLM provider: {selected}")
